services:
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment:
          - SECRET_KEY=django-insecure-k=c2v8cx7-$$j6y+qh=1yc@0$$i(@b#+)$d+yaou4uios@8t17k8
          - DEBUG=1
        volumes:
          - .:/code
        ports:
          - 8000:8000
        depends_on:
          - db
    db:
      image: postgres:17
      environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:
